Repository Loathing-Associates-Scripting-Society/yorick, pull requests merged in 2022-05, with the labels that each got.

#73 add undefile the crypt
  client/src/sections/QuestSection.tsx
  client/src/sections/quests/Level7.tsx
Labels: enhancement, quest

#71 Add Scotch's daylight shavings helmet.
  client/src/sections/ResourceSection.tsx
  client/src/sections/resources/DaylightShavingsHelmet.tsx
Labels: enhancement, IOTM

#70 adding npc prices for fireworks
  client/src/sections/resources/UndergroundFireworksShop.tsx
Labels: bug, IOTM

#61 integrating Advice Tooltips
  client/src/components/Tile.tsx
  client/src/components/Tooltips.tsx
  client/src/sections/resources/CosmicBowlingBall.tsx
  client/src/sections/resources/FreeFights.tsx
Labels: enhancement

#68 Quest Level 6
  client/src/sections/QuestSection.tsx
  client/src/sections/quests/Level6.tsx
Labels: enhancement, quest
