Repository Loathing-Associates-Scripting-Society/yorick, pull requests merged in 2022-01, with the labels that each got.

#26 extinguisher PR round 2
  client/src/sections/ResourceSection.tsx
  client/src/sections/resources/IndustrialFireExtinguisher.tsx
Labels: enhancement, quest

#47 Adding Hide Attribute
  client/src/components/Tile.tsx
Labels: enhancement

#46 Equip Item Attribute
  client/src/components/EquipLink.tsx
  client/src/components/Tile.tsx
  client/src/sections/resources/PowerfulGlove.tsx
Labels: enhancement, help wanted

#48 swapping to using hide attribute
  client/src/sections/resources/BackupCamera.tsx
  client/src/sections/resources/ColdMedicineCabinet.tsx
  client/src/sections/resources/CommerceGhost.tsx
  client/src/sections/resources/CosmicBowlingBall.tsx
  client/src/sections/resources/CursedMagnifyingGlass.tsx
  client/src/sections/resources/IndustrialFireExtinguisher.tsx
  client/src/sections/resources/PowerfulGlove.tsx
  client/src/sections/resources/UndergroundFireworksShop.tsx
Labels: enhancement

#51 Quest Standardization
  client/src/sections/quests/Level1.tsx
  client/src/sections/quests/Level2.tsx
  client/src/sections/quests/Level3.tsx
  client/src/sections/quests/Level4.tsx
  client/src/sections/quests/Level8.tsx
  client/src/sections/resources/CosmicBowlingBall.tsx
Labels: enhancement, quest

#65 Add Level 5 quest.
  client/src/components/QuestTile.tsx
  client/src/components/TileImage.tsx
  client/src/hooks/useFull.ts
  client/src/sections/QuestSection.tsx
  client/src/sections/quests/Level5.tsx
  client/src/util/makeValue.ts
Labels: enhancement, quest
